# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - relining_arm_controller

  relining_arm_controller:
    type: FollowJointTrajectory
    joints:
      - beam_joint
      - turn_table
      - boom_pitch
      - boom_inner_joint
      - grapple_slew
      - grapple_roll
      - grapple_pitch
    action_ns: follow_joint_trajectory
    default: true